# Generated by Django 3.2.13 on 2022-05-08 07:54

import datetime
from django.db import migrations, models
import portfolio_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_auto_20220501_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonialmodel',
            name='test_image_02',
            field=models.ImageField(default=datetime.datetime.now, upload_to=portfolio_api.models.TestimonialModel.file_upload_add),
        ),
    ]
