# Generated by Django 3.2.13 on 2022-07-21 06:03

from django.db import migrations, models
import portfolio_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0005_auto_20220614_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialmodel',
            name='test_image_02',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio_api.models.TestimonialModel.file_upload_add),
        ),
    ]
