# Generated by Django 3.2.13 on 2022-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0009_auto_20220724_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonialmodel',
            name='freelance_profile',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialmodel',
            name='social_media',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='testimonialmodel',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
