# Generated by Django 3.2.13 on 2022-08-24 10:08

from django.db import migrations, models
import file_convert.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=256, null=True)),
                ('ip_address', models.FloatField(blank=True, null=True)),
                ('conversion_limit', models.IntegerField(default=0)),
                ('paid_status', models.BooleanField(default=False)),
                ('file_upload', models.FileField(upload_to=file_convert.models.ConvertFile.file_upload_add)),
            ],
        ),
    ]
