# Generated by Django 3.2.13 on 2022-08-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_convert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertfile',
            name='file_name',
            field=models.CharField(blank=True, default='file name', max_length=256, null=True),
        ),
    ]
