# Generated by Django 3.2.13 on 2022-08-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_convert', '0003_auto_20220826_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertfile',
            name='file_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
