# Generated by Django 3.2.13 on 2022-08-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_convert', '0004_convertfile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertfile',
            name='get_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='convertfile',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
