# Generated by Django 3.2.13 on 2022-08-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_convert', '0005_auto_20220828_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertfile',
            name='text_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
