# Generated by Django 3.2.13 on 2022-08-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_convert', '0006_convertfile_text_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='convertfile',
            name='file_extension',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
