# Generated by Django 3.2.13 on 2023-10-29 08:29

from django.db import migrations, models
import portfolio_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=256, null=True)),
                ('subject', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hashed_link', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=False)),
                ('clicked', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=200)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(max_length=1000)),
                ('social_media', models.CharField(blank=True, max_length=256, null=True)),
                ('freelance_profile', models.CharField(blank=True, max_length=256, null=True)),
                ('recommendation', models.CharField(choices=[('HR', 'Highly Recommanded'), ('RE', 'Recommanded'), ('NR', 'Not Recommanded')], default='RE', max_length=2)),
                ('status', models.BooleanField(default=False)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('test_image_02', models.ImageField(blank=True, null=True, upload_to=portfolio_api.models.TestimonialModel.file_upload_add)),
            ],
        ),
    ]
