# Generated by Django 3.2.13 on 2024-06-29 13:39

from django.db import migrations, models
import portfolio_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('refrence', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('PS', 'Posted'), ('PN', 'Pending')], default='RE', max_length=2)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=portfolio_api.models.ProjectsModel.file_upload_add)),
            ],
        ),
    ]
