# Generated by Django 3.2.13 on 2024-06-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0002_projectsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsmodel',
            name='designation',
        ),
        migrations.AddField(
            model_name='projectsmodel',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
