# Generated by Django 3.2.13 on 2024-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_auto_20240629_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='video',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
