# Generated by Django 3.2.13 on 2022-06-14 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0003_testimonialmodel_test_image_02'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformmodel',
            name='city_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactformmodel',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactformmodel',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
