# Generated by Django 3.2.13 on 2022-06-14 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0004_auto_20220614_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='city_country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='ip_address',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
    ]
