# Generated by Django 3.2.13 on 2022-07-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0006_alter_testimonialmodel_test_image_02'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='city_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contactformmodel',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
