# Generated by Django 3.2.13 on 2022-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_api', '0008_auto_20220723_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmodel',
            old_name='city_country',
            new_name='city',
        ),
        migrations.AddField(
            model_name='contactformmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
